# Generated by Django 4.2.2 on 2023-08-03 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
